plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.28-beta'
}

version = '1.11.0'
group = 'com.hakimen'

repositories {
    mavenLocal()
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
    maven {
        name = "BlameJared"
        url = "https://maven.blamejared.com"
    }
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', 'kawaiidishes'
        }
        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', 'kawaiidishes'
        }
        data {
            data()
            programArguments.addAll '--mod', 'kawaiidishes', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        kawaiidishes {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

base {
    archivesName = 'KawaiiDishes'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

dependencies {
    implementation "software.bernie.geckolib:geckolib-neoforge-${mc_version}:${geckolib_version}"

    compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${mc_version}-neoforge:${jei_version}"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version   : mc_version,
            minecraft_version_range: mc_version_range,
            neo_version         : project.neoforge_version,
            neo_version_range   : project.neoforge_version,
            loader_version_range: project.neoforge_version,
            mod_id              : project.mod_id,
            mod_name            : project.mod_name,
            mod_license         : project.mod_license,
            mod_version         : project.mod_version,
            mod_authors         : project.mod_authors,
            mod_description     : project.mod_description,
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "kawaiidishes",
                "Specification-Vendor"    : "Hakimen",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "Hakimen",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
