org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false

mod_id=kawaiidishes
mod_name=Kawaii Dishes
mod_license=MIT
mod_version=1.11.0
mod_authors=Hakimen
mod_description=A mod about maids, food, and other stuff

neoforge_version=21.1.234
neoforge_snapshot=false

mc_version=1.21.1
mc_version_range=[1.21.1,1.22)

jei_version=19.27.0.343

geckolib_version=4.9
